- name: Create a VIP, pool, pool members, monitor and nodes
  hosts: bigips
  connection: local

  tasks:
      - name: Create a pool
        bigip_pool:
            lb_method: "round_robin"
            name: "FP_pool"
            password: "{{ bigip_password }}"
            server: "{{ inventory_hostname }}"
            slow_ramp_time: "120"
            user: "{{ bigip_username }}"
            validate_certs: "{{ validate_certs }}"
            monitor_type: and_list
            monitors: http
        delegate_to: localhost

      - name: Create node1
        bigip_node:
            host: "10.101.0.36"
            name: "FP_node-1"
            password: "{{ bigip_password }}"
            server: "{{ inventory_hostname }}"
            user: "{{ bigip_username }}"
            validate_certs: "{{ validate_certs }}"
        delegate_to: localhost

      - name: Create node2
        bigip_node:
            host: "10.101.0.37"
            name: "FP_node-2"
            password: "{{ bigip_password }}"
            server: "{{ inventory_hostname }}"
            user: "{{ bigip_username }}"
            validate_certs: "{{ validate_certs }}"
        delegate_to: localhost

      - name: Add nodes to pool
        bigip_pool_member:
            description: "webserver-1"
            host: "{{ item.host }}"
            name: "{{ item.name }}"
            password: "{{ bigip_password }}"
            pool: "FP_pool"
            port: "80"
            server: "{{ inventory_hostname }}"
            user: "{{ bigip_username }}"
            validate_certs: "{{ validate_certs }}"
        delegate_to: localhost
        with_items:
            - host: "10.101.0.36"
              name: "FP_node-1"
            - host: "10.101.0.37"
              name: "FP_node-2"

      - name: Create a VIP
        bigip_virtual_server:
            description: "FP_vip"
            destination: "10.211.0.36"
            password: "{{ bigip_password }}"
            name: "FP_vip"
            pool: "FP_pool"
            port: "8081"
            server: "{{ inventory_hostname }}"
            snat: "Automap"
            user: "{{ bigip_username }}"
            all_profiles:
                - "http"
            validate_certs: "{{ validate_certs }}"
        delegate_to: localhost
