- name: Set the NTP of the BIG-IP
  hosts: bigips
  connection: local

  tasks:
      - name: "Set NTP server"
        bigip_device_ntp: 
         ntp_servers: 
          - "192.168.100.116"
         password: "{{ bigip_password }}"
         server: "{{ inventory_hostname }}"
         user: "{{ bigip_username }}"
         validate_certs: "{{ validate_certs }}"
        delegate_to: localhost
